# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import PqCreation as pqc
import LoginScreen2 as lc
import XprtLoginControl as xlc
import XprtClientScript2 as xcs
import threading
import DataShare as ds
from tkinter import filedialog
import numpy as np
from PIL import Image,ImageTk
import cv2
import random
import RControl as rc
import AssembleData as ad
import KMController as km
import os
import pyperclip as pc
import GradientFrame as gf
import time
import sys




stCont=xlc.Controller()
varStore={}



if __name__ == "__main__":
    host='localhost'
    port=9898

    app = QApplication(sys.argv)
    MainWindow = QMainWindow()


    MainWindow.show()

    print(sys.exit(app.exec_()))





